### ISSUE TITLE
Compiled scrypt is slow

### ISSUE THREAD

**Issue by btcontract** [ElementsProject/libwally-core#219] opened 2020-08-24 13:50 UTC
Hello,

we currently try to compile libwally into an android project, we could get our fork to a state where it compiles successfully and passes tests with the following `CMakeLists` file: https://github.com/engenegr/libwally-core/blob/5bd3be99bcdcbb2850dbe56e64c968373560a295/CMakeLists.txt

However, when running this scrypt test: https://github.com/btcontract/firebird/blob/master/app/src/androidTest/java/com/btcontract/wallet/NativeLibsSpec.java#L30 with our NDK-compiled version is takes ~5x more time than pre-compiled libwally binaries.

Could you please suggest what could be the cause of this?
Thanks!

**Comment by engenegr** [comment] 2020-08-24 13:52
Suggestions about possible clang flags are very welcome!

**Comment by jgriffiths** [comment] 2020-08-24 21:13
Hi @engenegr if I understand correctly you are building using cmake without going through configure, so the configure script isn't enabling the optimised and assembly code paths for you.

The best fix is to use cmake to invoke configure/make to build wally since that will always be up to date. Something like the suggested answer here https://stackoverflow.com/questions/5971921/building-a-library-using-autotools-from-cmake.

Otherwise, you'll need to build the library using configure manually, and then take the generated config.h file from the build result and use that to build with, make sure any file specific compile flags are duplicated etc. That may work but its not a supported way of building and we can't offer any help with problems you encounter doing that.

I'm closing this for now, if you find that scrypt is slow even when the library is build through autotools as per the README, feel free to re-open.

**Closed by jgriffiths** 2020-08-24 21:13 UTC

**Comment by jgriffiths** [comment] 2020-08-25 04:09
Please also see https://github.com/greenaddress/GreenBits/blob/master/app/prepare_libwally_clang.sh from the old greenbits app which is how we used to build wally for use in that android project (when not using the prebuilt binaries).

Also note if you will be doing anything with PSBTs you will want to update to master since the interface has changed a lot ince the last release.

**Comment by engenegr** [comment] 2020-08-25 07:53
@jgriffiths I prefer to use once-made configuration header files to be sure nothing is changed by occasion. Because I hade already working configs like `libsecp256k1-config.h` and on the contrary, libraries configured in place didn't work, I have left `libsecp256k1-config.h` close as much to the original cmake - compiled libsecp256k1 library I had. The same applicable to libwally configs, I'm just finding working configuration and stick to it. _I found this working configuration by using autotools initially_. But thank you for your directions, I maybe reconsider build system files later.

I'm aware of this script https://github.com/greenaddress/GreenBits/blob/master/app/prepare_libwally_clang.sh  but I don't see any meaningful information in it related to clang-specific flags.

**Comment by jgriffiths** [comment] 2020-08-26 07:09
@engenegr I can only assume your configure run disabled the assembly somehow, or didnt pick up the arch flags. see android_build_wally() in tools/android_helpers.sh and make sure you are passing in the correct arch and --with-asm flags for your device(s).

At least, i would try with a version built by that script and see if the performance problems persist, that may help you track the cause down.

**Comment by engenegr** [comment] 2020-08-26 13:51
@jgriffiths thanks a lot for advice.

I figured out that I need to swich `set(CMAKE_BUILD_TYPE 'Release')` to test optimised build.
