### ISSUE TITLE
OS X - test_clear fails

### ISSUE THREAD

**Issue by isghe** [ElementsProject/libwally-core#2] opened 2017-07-25 10:34 UTC
test_clear fails both on OS X El Capitan (Version 10.11.6) with Xcode Version 8.2.1 (8C1002), and macOS Sierra 10.12.5 (16F73) with Xcode Version 8.3.3 (8E3004b).

```
$ make check
Making check in src
Making check in secp256k1
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
============================================================================
Testsuite summary for libsecp256k1 0.1
============================================================================
# TOTAL: 0
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS check-local
FAIL: test_clear
============================================================================
Testsuite summary for libwallycore 0.1
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

src/test-suite.log:

```
$ cat src/test-suite.log
==========================================
   libwallycore 0.1: src/test-suite.log
==========================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_clear
================

Found bip39_mnemonic_to_bytes secret at stack position 523592
7f, 7f, 7f, 7f, 7f, 7f, 7f, 7f, 7f, 7f, 7f, 7f, 7f, 7f, 7f, 7f, 
test_bip39 clear() test failed!
FAIL test_clear (exit status: 1)
```

**Comment by jgriffiths** [comment] 2017-07-27 06:31
Hi @isghe can you give the environment vars you are using (CC, CFLAGS etc) as well as the configure flags you used?

**Comment by isghe** [comment] 2017-07-27 13:15
Hi @jgriffiths,
I am on  OS X El Capitan (Version 10.11.6) with Xcode Version 8.2.1 (8C1002),

`$ ./configure --enable-debug --enable-export-all --enable-swig-python --enable-coverage`

The config.log: https://pastebin.com/WWm9eHZp

and the gcc version (that is clang)

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Thanks

**Comment by jgriffiths** [comment] 2017-08-01 04:43
Hi @isghe,

Turns out this is caused by the varargs implementation on clang copying arguments. The fix will be checked in shortly.

**Comment by jgriffiths** [comment] 2017-08-03 13:59
Should be fixed now.

**Closed by jgriffiths** 2017-08-03 13:59 UTC

**Comment by isghe** [comment] 2017-08-03 14:42
great, it's working good now 👍
