### ISSUE TITLE
MacOS compilation issue?

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/libwally-core#229] opened 2020-09-23 07:30 UTC
https://github.com/ElementsProject/lightning/pull/4078#issuecomment-697074784

**Comment by kallewoof** [comment] 2020-09-23 07:57
libwally-core current master compiles fine for me

**Comment by kallewoof** [comment] 2020-09-23 08:07
I suspect config.h generation hiccup on lightning side. The lightning side V=1 make output for the offending line is

> libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../../libwally-core/src -I../../../libwally-core -I../../../libwally-core/src/ccan -DWALLY_CORE_BUILD=1 -D_DEFAULT_SOURCE=1 -Wall -Wextra -Wpedantic -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wformat -Wformat-security -Wformat-nonliteral -O0 -ggdb -DBUILD_ELEMENTS=1 -flax-vector-conversions -Wno-unused-function -Wno-long-long -Wno-overlength-strings -Wno-variadic-macros -fvisibility=hidden -std=c99 -MT libwallycore_la-internal.lo -MD -MP -MF .deps/libwallycore_la-internal.Tpo -c ../../../libwally-core/src/internal.c -o libwallycore_la-internal.o

If I grep the entire lightning folder for 'HAVE_MEMSET_S' I get 
```
./external/libwally-core/autom4te.cache/traces.1:m4trace:configure.ac:232: -1- AH_OUTPUT([HAVE_MEMSET_S], [/* Define to 1 if you have the `memset_s\' function. */
./external/libwally-core/autom4te.cache/traces.1:@%:@undef HAVE_MEMSET_S])
./external/libwally-core/src/config.h.in:#undef HAVE_MEMSET_S
./external/libwally-core/src/internal.c:#elif defined(HAVE_MEMSET_S)
./external/libwally-core/src/config.h.in~:#undef HAVE_MEMSET_S
./external/x86_64-apple-darwin19.5.0/libwally-core-build/config.status:D["HAVE_MEMSET_S"]=" 1"
./external/x86_64-apple-darwin19.5.0/libwally-core-build/config.log:| #define HAVE_MEMSET_S 1
./external/x86_64-apple-darwin19.5.0/libwally-core-build/config.log:| #define HAVE_MEMSET_S 1
./external/x86_64-apple-darwin19.5.0/libwally-core-build/config.log:| #define HAVE_MEMSET_S 1
./external/x86_64-apple-darwin19.5.0/libwally-core-build/config.log:| #define HAVE_MEMSET_S 1
./external/x86_64-apple-darwin19.5.0/libwally-core-build/config.log:| #define HAVE_MEMSET_S 1
./external/x86_64-apple-darwin19.5.0/libwally-core-build/config.log:| #define HAVE_MEMSET_S 1
./external/x86_64-apple-darwin19.5.0/libwally-core-build/config.log:#define HAVE_MEMSET_S 1
./external/x86_64-apple-darwin19.5.0/libwally-core-build/src/config.h:#define HAVE_MEMSET_S 1
grep: ./external/x86_64-apple-darwin19.5.0/libwally-core-build/src/secp256k1/.libs/libsecp256k1.la: No such file or directory
./external/libsodium/src/libsodium/sodium/utils.c:#elif defined(HAVE_MEMSET_S)
```

The same for libwally-core master:
```
./autom4te.cache/traces.1:m4trace:configure.ac:232: -1- AH_OUTPUT([HAVE_MEMSET_S], [/* Define to 1 if you have the `memset_s\' function. */
./autom4te.cache/traces.1:@%:@undef HAVE_MEMSET_S])
./src/config.h:/* #undef HAVE_MEMSET_S */
./src/config.h.in:#undef HAVE_MEMSET_S
./src/internal.c:#elif defined(HAVE_MEMSET_S)
```

**Comment by kallewoof** [comment] 2020-09-23 08:18
libwally-core master:
```
configure:15175: checking for memset_s
configure:15175: gcc -o conftest -g -O2  -D_FORTIFY_SOURCE=2 -O2  conftest.c  >&5
configure:15175: $? = 0
configure:15175: result: yes
```

lightning external/x86_64-apple-darwin19.5.0/libwally-core-build/config.log:
```
configure:15170: checking for memset_s
configure:15170: cc -o conftest -std=c99   -O0 -ggdb conftest.c  >&5
configure:15170: $? = 0
configure:15170: result: yes
```

Weird...

**Comment by kallewoof** [comment] 2020-09-23 08:19
I reconfigured libwally-core again and re-made and such, and now the grep -r gives
```
./autom4te.cache/traces.1:m4trace:configure.ac:232: -1- AH_OUTPUT([HAVE_MEMSET_S], [/* Define to 1 if you have the `memset_s\' function. */
./autom4te.cache/traces.1:@%:@undef HAVE_MEMSET_S])
./config.status:D["HAVE_MEMSET_S"]=" 1"
./config.log:| #define HAVE_MEMSET_S 1
./config.log:| #define HAVE_MEMSET_S 1
./config.log:| #define HAVE_MEMSET_S 1
./config.log:| #define HAVE_MEMSET_S 1
./config.log:| #define HAVE_MEMSET_S 1
./config.log:| #define HAVE_MEMSET_S 1
./config.log:#define HAVE_MEMSET_S 1
./src/config.h:#define HAVE_MEMSET_S 1
./src/config.h.in:#undef HAVE_MEMSET_S
./src/internal.c:#elif defined(HAVE_MEMSET_S)
```

**Comment by jgriffiths** [comment] 2020-09-23 08:38
@kallewoof can you see if memset_s in string.h is wrapped in _XOPEN_SOURCE or some other versioned macro check that might need to be provided?

**Comment by jgriffiths** [comment] 2020-09-23 09:30
@kallewoof can you also see if taking ` CFLAGS=-std=c99` out of `external/Makefile` in c-lightning fixes it?

**Comment by jgriffiths** [comment] 2020-09-23 09:38
@kallewoof if you can try the patch in this PR https://github.com/ElementsProject/libwally-core/pull/230 I suspect that might fix it.

**Comment by kallewoof** [comment] 2020-09-23 09:39
Huh, yeah, memset_s is C11: https://en.cppreference.com/w/c/string/byte/memset

Trying without c99 part does indeed stop giving the error.

**Comment by kallewoof** [comment] 2020-09-23 09:41
So, either (1) libwally-core requires C11 and this is a lightning issue, or (2) libwally-core supports C99 in which case the `HAVE_MEMSET_S` part should be unset for C99 case.

**Comment by kallewoof** [comment] 2020-09-23 09:42
Didn't see #230 comment until now. Trying.

**Comment by jgriffiths** [comment] 2020-09-23 09:44
> So, either (1) libwally-core requires C11 and this is a lightning issue, or (2) libwally-core supports C99 in which case the `HAVE_MEMSET_S` part should be unset for C99 case.

Wally should only require c99, with it set then configure shouldn't be reporting that memset_s is available to us really.

**Comment by kallewoof** [comment] 2020-09-23 09:45
@jgriffiths No go on #230. I think the config stuff isn't present at the top of the file, causing HAVE_MEMSET_S to not be set. This
```C
#define __STDC_WANT_LIB_EXT1__ 1
#include <string.h>
[...]
```
works though.

**Comment by kallewoof** [comment] 2020-09-23 09:54
Isn't this a problem where the libwally-core configure script is not called with -std=c99 flag tho?

**Comment by jgriffiths** [comment] 2020-09-23 10:06
@kallewoof Thanks for your help testing this, I don't have a mac box handy to debug myself.

We use `AC_CHECK_FUNCS` from configure which appears to a) ignore the CFLAGS and b) test for the functions existence by linking. Since it ignores `std=c99` it compiles and links fine in the configure check without seeing the declaration (which requires `__STDC_WANT_LIB_EXT1__` to be defined). When it then compiles the source it gives an error as under C99 the declaration must be visible.

I've force pushed another version to the above PR which should fix it I think, do you mind confirming?

**Comment by kallewoof** [comment] 2020-09-23 10:20
The resulting test C script for this test is the following:
```C
/* confdefs.h */
#define PACKAGE_NAME "libwallycore"
#define PACKAGE_TARNAME "libwallycore"
#define PACKAGE_VERSION "0.7.8"
#define PACKAGE_STRING "libwallycore 0.7.8"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "libwallycore"
#define VERSION "0.7.8"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_UNALIGNED_ACCESS 1
#define HAVE_MMAP 1
#define HAVE_POSIX_MEMALIGN 1
/* end confdefs.h.  */
/* Define memset_s to an innocuous variant, in case <limits.h> declares memset_s.
   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
#define memset_s innocuous_memset_s

/* System header to define __stub macros and hopefully few prototypes,
    which can conflict with char memset_s (); below.
    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
    <limits.h> exists even on freestanding compilers.  */

#ifdef __STDC__
# include <limits.h>
#else
# include <assert.h>
#endif

#undef memset_s

/* Override any GCC internal prototype to avoid an error.
   Use char because int might match the return type of a GCC
   builtin and then its argument prototype would still apply.  */
#ifdef __cplusplus
extern "C"
#endif
char memset_s ();
/* The GNU C library defines this for functions which it implements
    to always fail with ENOSYS.  Some functions are actually named
    something starting with __ and the normal name is an alias.  */
#if defined __stub_memset_s || defined __stub___memset_s
choke me
#endif

int
main ()
{
return memset_s ();
  ;
  return 0;
}
```
which... i mean, it's declaring `memset_s` above, so it obviously compiles, and since `memset_s` does exist, linker succeeds too. Maybe I'm missing something brilliant here.

**Comment by jgriffiths** [comment] 2020-09-23 10:29
> Maybe I'm missing something brilliant here.

This code is only testing that the linker can resolve the symbol, since it provides a definition for the function itself (`char memset_s ();`). So this doesn't catch that the definition isn't available without the extra define. Standards are such fun lol.

If the revised patch linked above fixes this I'll merge it immediately.

**Comment by kallewoof** [comment] 2020-09-23 10:42
I believe it does, but I'm running into unrelated issues causing compile errors.

**Comment by kallewoof** [comment] 2020-09-23 10:46
Confirmed that it does resolve the problem.

**Comment by jgriffiths** [comment] 2020-09-23 10:56
> Confirmed that it does resolve the problem.

Thanks for the quick help debugging @kallewoof , closing as the workaround is merged and the lightning issue commented.

**Closed by jgriffiths** 2020-09-23 10:56 UTC
